### ISSUE TITLE
Fully Developed Implementation of SRGAN

### ISSUE THREAD

**Issue by rmalav15** [huangzehao/Super-Resolution.Benckmark#5]
Hi @huangzehao 
You efforts for gathering all this material in this repo is deeply appreciated. As you mentioned, that your implementation of [SRGAN ](https://github.com/huangzehao/torch-srgan) does not have very good result.
I just wanted to know whether this implementation (for SRGAN not SRResNet) exactly follow [the original paper](https://arxiv.org/abs/1609.04802) or you took some liberties. 

Can you please also let me know if you are aware of any fully developed (or close) and tested implementation (In any deep learning framework ) of SRGAN (not only SRResNet)?

Thanks

**Comment by huangzehao** [comment]
Hi, I implement SRGAN follow the original paper. But it was about half year ago. Since I am not familiar with the training of GAN, I didn't spend much time to adjust the training.
`Can you please also let me know if you are aware of any fully developed (or close) and tested implementation (In any deep learning framework ) of SRGAN (not only SRResNet)?`
Sorry, I don't understand your mean.  I may try to implement SRGAN if I have time.

**Comment by ZJiaQi** [comment]
Hi,thanks for your helpful codes about SRGAN. 
Can you please let me know the results of PSNR and SSIM using the detaset of NIV2k ,while in your experiments?
Thanks.
